import { ReactNode } from 'react'
import './globals.css'
import {Roboto} from 'next/font/google'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const myFont = Roboto({weight:"400",subsets:['latin']})

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={`${myFont.className}`}>
        {children}
      </body>
    </html>
  )
}
